#!/usr/bin/bash -x

source "$(dirname "${BASH_SOURCE[0]}")"/../../scripts/test-lib.sh

# Update cleanup function parameters on each test artifact change
trap 'cleanup_path "*.json"' 'EXIT'

# jq selector matching the lorax-script stage that runs the pregen_ssh_host_keys
# helper (which generates the static ssh host keys embedded in the image).
PREGEN_STAGE='.pipelines[] | .stages[]? | select(.type == "org.osbuild.lorax-script") | select(.options.product.name | test("pregen_ssh_host_keys"))'

# Test 1: enabled via manifest option (auth.sshd_static_host_keys: true) ->
# the host keys are generated at build time (stage present).
echo_log "Test 1: auth.sshd_static_host_keys: true generates static host keys..."
build --dry-run --osbuild-manifest enabled.json enabled.aib.yml "$NO_CTR_NAME" out
assert_has_file enabled.json
assert_jq enabled.json "$PREGEN_STAGE" \
    "Expected pregen_ssh_host_keys stage when sshd_static_host_keys is true"
echo_log "Static host keys correctly generated when enabled"

# Test 2: disabled via manifest option (auth.sshd_static_host_keys: false) ->
# the host keys are NOT generated at build time (stage absent).
echo_log "Test 2: auth.sshd_static_host_keys: false does not generate static host keys..."
build --dry-run --osbuild-manifest disabled.json disabled.aib.yml "$NO_CTR_NAME" out
assert_has_file disabled.json
assert_jq_not disabled.json "$PREGEN_STAGE" \
    "Did not expect pregen_ssh_host_keys stage when sshd_static_host_keys is false"
echo_log "Static host keys correctly skipped when disabled"

# Test 3: default (option not set) -> host keys are generated (default is true).
echo_log "Test 3: default (option unset) generates static host keys..."
build --dry-run --osbuild-manifest default.json default.aib.yml "$NO_CTR_NAME" out
assert_has_file default.json
assert_jq default.json "$PREGEN_STAGE" \
    "Expected pregen_ssh_host_keys stage by default"
echo_log "Static host keys correctly generated by default"

echo_pass "Static ssh host key generation option validated successfully."
