# Target for the TI SK-AM62 Evaluation Board (https://www.ti.com/tool/SK-AM62)
version: '2'
mpp-vars:
  k3_board: 'am62x_evm_gp'

# To derive and override mpp vars we move the overrides to an include file
pipelines:
  - mpp-import-pipelines:
      path: include/k3.ipp.yml
