# Target for the TI SK-TDA4VM Evaluation Board (https://www.ti.com/tool/SK-TDA4VM)
version: '2'
mpp-vars:
  k3_board: 'j721e_sk_gp'

# To derive and override mpp vars we move the overrides to an include file
pipelines:
  - mpp-import-pipelines:
      path: include/k3.ipp.yml
